import 'select_services.dart';
import 'transaction_existing.dart';
import 'globals.dart' as globals;
import 'new_order.dart';

globals_clear_Function() {
  globals.completed = "";
  globals.flag = "";
  globals.status = "";
  globals.customer_name = "";
  globals.order_no = "";
  globals.customer_mobile_no = "";
  globals.order_date = "";
  globals.schedule_dt = "";
  globals.CHANNEL = "";
  globals.REFERAL_DOCTOR = "";
  globals.customer_address = "";
  globals.service_name = "";
  globals.PAID_AMOUNT = "";
  globals.outstanding_due = "";
  globals.customer_gender = "";
  globals.customer_age = "";
  // globals.DISPLAY_NAME = "";
  // globals.USER_NAME = "";
  // globals.USER_ID = "";
  globals.selectDate = "";
  // globals.LOCATION_NAME = "";
  globals.order_id = "";
  globals.assign_phlebotomist_id = "";
  globals.gender = "";
  globals.Mobile_Number = "";
  globals.Selected_Title = "";
  globals.Selected_Pincode = "";
  globals.Selected_Date = "";
  globals.LOCATIONID = "";
  globals.user_name = "";
  globals.umr_no = "";
  globals.option = "";
  globals.REFERAL_SOURCE_ID = "";
  globals.family_members_user_name = "";
  globals.family_members_user_dob = "";
  globals.family_members_age = "";
  globals.family_members_user_phone = "";
  globals.family_members_gender = "";
  globals.family_members_user_email = "";
  globals.family_members_user_address = "";
  globals.family_members_umr_no = "";
  globals.customer_id = "";
  globals.Price_new_order = "";
  globals.VACCUTAINER_CUNT_for_New_Order = "";
  globals.Barcode_for_New_Order = "";
  globals.SERVICE_ID_by_new_order = "";
  globals.SPECIMEN_ID_by_new_order = "";
  globals.VACCUTAINER_ID_by_new_order = "";
  globals.SERVICE_NAME_by_new_order = "";
  globals.SPECIMEN_NAME_by_new_order = "";
  globals.VACCUTAINER_by_new_order = "";
  globals.Billing_pricenew = "";
  globals.Price_new_order = "";
  globals.discount_policy_id = "";
  globals.REFRL_ID = "";
  globals.AUTH_NAME = "";
  globals.AUTH_ID = "";
  globals.ID = "";
  globals.AREA_ID = "";
  cash_Controller.text = "";
  due_Controller.text = "";
  Mobile_Controller.clear();
  myList.clear();
  globals.selected_date = "";
  globals.age = "";
  globals.mobile_no = "";
  globals.refferal_name = "";
  globals.registration_no = "";
}

globals_value_clear() {
  globals.Price_new_order = "";
  globals.VACCUTAINER_CUNT_for_New_Order = "";
  globals.Barcode_for_New_Order = "";
  globals.SERVICE_ID_by_new_order = "";
  globals.SPECIMEN_ID_by_new_order = "";
  globals.VACCUTAINER_ID_by_new_order = "";
  globals.SERVICE_NAME_by_new_order = "";
  globals.SPECIMEN_NAME_by_new_order = "";
  globals.VACCUTAINER_by_new_order = "";
  globals.Billing_pricenew = "";
  globals.Price_new_order = "";
  globals.discount_policy_id = "";
  globals.REFRL_ID = "";
  globals.AUTH_NAME = "";
  globals.AUTH_ID = "";
}
